apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: ade-fcm
  labels:
    app: spark
    role: master
    project: ade-fcm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      name: webui
  selector:
    app: spark
    role: master

---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-ui
  namespace: ade-fcm
  labels:
    app: spark
    role: master
    project: ade-fcm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: webui
  selector:
    app: spark
    role: master

---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  namespace: ade-fcm
  labels:
    app: spark
    role: worker
    project: ade-fcm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8081
      targetPort: 8081
      name: webui
  selector:
    app: spark
    role: worker

---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  namespace: ade-fcm
  labels:
    app: jupyter
    project: ade-fcm
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30888
      name: notebook
  selector:
    app: jupyter

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: ade-fcm
  labels:
    app: mlflow
    project: ade-fcm
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      name: tracking
  selector:
    app: mlflow

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-ui
  namespace: ade-fcm
  labels:
    app: mlflow
    project: ade-fcm
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      name: ui
  selector:
    app: mlflow
